
# ===== Spring核心配置 ======
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ggusercenter?serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root